### ISSUE TITLE
What is this code????

### ISSUE THREAD

**Issue by SuperS0n1k** [itss0n1c/itss0n1c.github.io#1]
I was scrolling through IPAcandy’s vendor js file and something caught my eye; the word “illegal”
What is this peice of js code? Please tell in detail. (I’m just interested since i am also a JailBreak dev)

**Comment by itss0n1c** [comment]
@SuperS0n1k The vendor js file is a bundled copy of [highlight.js](https://github.com/highlightjs/highlight.js/).
The `illegal` key used around is to do with escape characters that would get ignored if found. I'd suggest checkout out their source for more details.

**Comment by SuperS0n1k** [comment]
Also how can i put new system files into ios using js?
